name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the `main` branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Kaggle JSON
        #context: .  # Path to the Dockerfile
        run: |
          echo "${{ secrets.KAGGLE_JSON }}" > kaggle.json
          chmod 600 kaggle.json

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Path to the Dockerfile
          push: true  # Push the image to Docker Hub
          tags: |
            ahmed3991/codestral-22b:latest
            ahmed3991/codestral-22b:${{ github.sha }}
